name: pdcBech32
version: 0.2.0
description: Library implementing Bitcoins BIP173 (Bech32 encoding) specification in a Flutter friendly fashion.
homepage: https://github.com/pdc-flutter/pdcBech32.git

dependencies:
    convert: '>=1.0.0 <=3.0.0'

dev_dependencies:
    hex: ^0.2.0
    pedantic: ^1.11.0
    test: ^1.16.5

environment:
  sdk: ">=2.12.0 <3.0.0"
